name: bridge
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  embed_annotation: ^1.2.3
  ffsds3:
    path: ../ffsds3
  using: ^1.0.5

dev_dependencies:
  build_runner: ^2.11.1
  embed: ^1.6.4
  leancode_lint: ^21.0.0+1
  lints: ^6.1.0
